### ISSUE TITLE
Flutter GUI (Android)

### ISSUE THREAD

**Issue by JMarts32** [ISIS3510-Seccion-3-Grupo-32/Documentation#10]
The GUI for answering the BQ's type 2 needs to be implemented for Android using Flutter.

**Comment by jfpatino01** [comment]
Type 2 BQs that must be answered:

    How many crimes have been committed on that street, that have been reported, in the last week?

    In which of the four categories (felonies, misdemeanors, felony-misdemeanors, and infractions) is the crime classified?

It will be also uploaded to the Repo for iOS and screenshots in the MS7
