### ISSUE TITLE
Database Structure for the ones we define

### ISSUE THREAD

**Issue by jfpatino01** [ISIS3510-Seccion-3-Grupo-32/Documentation#14]
We define the structure

    PQRS DB
    Performance DB
    Logs DB
    Users DB
    Analytics DB
    Itineraries DB

**Comment by jfpatino01** [comment]
![Image](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/64269726/4c81f8f8-eca9-4cdc-80ac-8d7956cd1659)

**Comment by JMarts32** [comment]
LGTM
