### ISSUE TITLE
Select Icon of App

### ISSUE THREAD

**Issue by jfpatino01** [ISIS3510-Seccion-3-Grupo-32/Documentation#15]
Select from the choices or a new one the Icon for the App which will be used on the App Store / Play Store and also within

**Comment by Gustavo-Tabima** [comment]
i'll leave my purposals here

![Imagen de WhatsApp 2023-09-22 a las 12 32 59](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/60206565/12cfd02a-8970-45b4-b4f9-87559bdd2599)
![Imagen de WhatsApp 2023-09-22 a las 12 25 07](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/60206565/950ba196-f01d-42d4-ab3f-685ec6cdd6b9)
![Imagen de WhatsApp 2023-09-22 a las 12 21 58](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/60206565/1de6e610-2c4c-42c5-9cbf-626d496d8bfb)
![Imagen de WhatsApp 2023-09-22 a las 17 55 55](https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/assets/60206565/b61d03b0-5df7-4dfa-8b2c-3a962f06b110)
