### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by JMarts32** [ISIS3510-Seccion-3-Grupo-32/Documentation#9]
The backend needs to be implemented in the `Backend` repo

**Comment by jfpatino01** [comment]
This BackEnd must follow the structure defined in the Repo. It will consist of both the Analytics and the Business side together.

It is available in the following part of the wiki:
https://github.com/ISIS3510-Seccion-3-Grupo-32/Documentation/wiki/Micro%E2%80%90Sprint-7#architectural-design
